/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.zebalu.aoc2023;

import java.time.Duration;
import java.time.Instant;
import java.util.Collections;
import java.util.function.Consumer;

public class App {

    public static void main(String[] args) {
        exec(new DisplayData(1, "Trebuchet?!", Day01::main));
    }
    
    private static void exec(DisplayData dd) {
    	String title = String.format(" Day %02d: %s ", dd.number(), dd.name());
    	StringBuffer titleLine = new StringBuffer();
    	titleLine.append(repeat("#", (80-title.length())/2));
    	titleLine.append(title);
    	titleLine.append(repeat("#", 80-titleLine.length()));
    	System.out.println(titleLine.toString());
    	Instant start = Instant.now();
    	dd.main().accept(new String[] {});
    	Instant end = Instant.now();
    	System.out.println(repeat("-", 80));
    	System.out.println(Duration.between(start, end).toMillis()+" ms");
    	System.out.println(repeat("*", 80));
    }
    
    private static String repeat(String data, int times) {
    	return String.join("", Collections.nCopies(times, data));
    }
    
    record DisplayData(int number, String name, Consumer<String[]> main) {}
}
