/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.zebalu.aoc2023;

import java.util.function.Consumer;

public class App {

    public static void main(String[] args) {
        exec(Day01::main);
    }
    
    private static void exec(Consumer<String[]> main) {
    	main.accept(new String[] {});
    }
}
